name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        ##TODO
        uses: docker://rhysd/actionlint:latest

      - name: Run Checkstyle
        ##TODO
        run: mvn checkstyle:checkstyle


      - name: Upload Checkstyle Result
        ##TODO
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CheckstyleReport
          path: target/checkstyle-result.xml


      - name: Run Maven Test
        ##TODO
        run: mvn test

      - name: Jacoco Report
        ##TODO
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: target/site/jacoco/index.html